import { APIType } from "../types";

export const APIList: APIType[] = [
  {
    name: "Dog Facts",
    category: "Animal",
    key: false,
    link: "https://dukengn.github.io/Dog-facts-API/",
    description: "An API that will return random facts about dog.",
    comments: [],
    likes: 0,
  },
  {
    name: "Cat Facts",
    category: "Animal",
    key: false,
    link: "https://alexwohlbruck.github.io/cat-facts/",
    description:
      "Using a combination of Node.js, Angular, and Tasker, this app will combine APIs and Services from the web to do just one thing… send cat facts.",
    comments: [],
    likes: 0,
  },

  {
    name: "eBird",
    category: "Animal",
    key: false,
    link: "https://documenter.getpostman.com/view/664302/S1ENwy59",
    description:
      "Get the list of recent observations (up to 30 days ago) of birds seen in a country, state, county, or location. Results include only the most recent observation for each species in the region specified.",
    comments: [],
    likes: 0,
  },
  {
    name: "FishWatch",
    category: "Animal",
    key: false,
    link: "https://www.fisheries.noaa.gov/topic/sustainable-seafood",
    description: "Information and pictures about individual fish species",
    comments: [],
    likes: 0,
  },
  {
    name: "Movebank",
    category: "Animal",
    key: false,
    link: "https://github.com/movebank/movebank-api-doc",
    description: "Movement and Migration data of animals",
    comments: [],
    likes: 0,
  },
  {
    name: "AniAPI",
    category: "Anime",
    key: false,
    link: "https://aniapi.com/docs/",
    description: "Anime discovery, streaming & syncing with trackers",
    comments: [],
    likes: 0,
  },
  {
    name: "AniDB",
    category: "Anime",
    key: true,
    link: "https://wiki.anidb.net/HTTP_API_Definition",
    description: "Anime Database",
    comments: [],
    likes: 0,
  },
  {
    name: "AniList",
    category: "Anime",
    key: false,
    link: "https://github.com/AniList/ApiV2-GraphQL-Docs",
    description: "Anime discovery & tracking",
    comments: [],
    likes: 0,
  },
  {
    name: "AnimeChan",
    category: "Anime",
    key: false,
    link: "https://github.com/rocktimsaikia/animechan",
    description: "Anime discovery & tracking",
    comments: [],
    likes: 0,
  },
  {
    name: "AnimeFacts",
    category: "Anime",
    key: false,
    link: "https://chandan-02.github.io/anime-facts-rest-api/",
    description: "Anime Facts (over 100+)",
    comments: [],
    likes: 0,
  },
  {
    name: "NekosBest",
    category: "Anime",
    key: false,
    link: "https://docs.nekos.best/",
    description: "Neko Images & Anime roleplaying GIFs",
    comments: [],
    likes: 0,
  },
  {
    name: "Shikimori",
    category: "Anime",
    key: false,
    link: "https://shikimori.one/api/doc",
    description: "Anime discovery, tracking, forum, rates",
    comments: [],
    likes: 0,
  },
  {
    name: "Waifu.pics",
    category: "Anime",
    key: false,
    link: "https://waifu.pics/docs",
    description: "Image sharing platform for anime images",
    comments: [],
    likes: 0,
  },
  {
    name: "AbuseIPDB",
    category: "Anti-Malware",
    key: true,
    link: "https://docs.abuseipdb.com/#introduction",
    description: "IP/domain/URL reputation",
    comments: [],
    likes: 0,
  },
  {
    name: "URLhaus",
    category: "Anti-Malware",
    key: false,
    link: "https://urlhaus-api.abuse.ch/",
    description: "Bulk queries and Download Malware Samples",
    comments: [],
    likes: 0,
  },
  {
    name: "MalDatabase",
    category: "Anti-Malware",
    key: true,
    link: "https://malshare.com/doc.php",
    description: "Malware Archive / file sourcing",
    comments: [],
    likes: 0,
  },
  {
    name: "Google Safe Browsing",
    category: "Anti-Malware",
    key: true,
    link: "https://developers.google.com/safe-browsing/",
    description: "Google Link/Domain Flagging",
    comments: [],
    likes: 0,
  },
  {
    name: "Metacert",
    category: "Anti-Malware",
    key: true,
    link: "https://metacert.com/",
    description: "Metacert Link Flagging",
    comments: [],
    likes: 0,
  },
  {
    name: "Scanii",
    category: "Anti-Malware",
    key: true,
    link: "https://docs.scanii.com/",
    description: "Bulk queries and Download Malware Samples",
    comments: [],
    likes: 0,
  },
  {
    name: "Web of Trust",
    category: "Anti-Malware",
    key: true,
    link: "https://support.mywot.com/hc/en-us/sections/360004477734-API-",
    description: "IP/domain/URL reputation",
    comments: [],
    likes: 0,
  },

  {
    name: "Art Institute of Chicago",
    category: "Art & Design",
    key: false,
    link: "https://api.artic.edu/docs/",
    description: "Art",
    comments: [],
    likes: 0,
  },
  {
    name: "Colormind",
    category: "Art & Design",
    key: false,
    link: "http://colormind.io/api-access/",
    description: "Color scheme generator",
    comments: [],
    likes: 0,
  },
  {
    name: "ColourLovers",
    category: "Art & Design",
    key: false,
    link: "https://www.colourlovers.com/api",
    description: "Get various patterns, palettes and images",
    comments: [],
    likes: 0,
  },
  {
    name: "Cooper Hewitt",
    category: "Art & Design",
    key: true,
    link: "https://collection.cooperhewitt.org/api",
    description: "Smithsonian Design Museum",
    comments: [],
    likes: 0,
  },
  {
    name: "EmojiHub",
    category: "Art & Design",
    key: true,
    link: "https://pro.europeana.eu/page/search",
    description: "European Museum and Galleries content	",
    comments: [],
    likes: 0,
  },
  {
    name: "Lordicon",
    category: "Art & Design",
    key: false,
    link: "https://lordicon.com/",
    description: "Icons with predone Animations",
    comments: [],
    likes: 0,
  },
  {
    name: "Metropolitan Museum of Art",
    category: "Art & Design",
    key: false,
    link: "https://metmuseum.github.io/",
    description: "Met Museum of Art",
    comments: [],
    likes: 0,
  },
  {
    name: "Word Cloud",
    category: "Art & Design",
    key: false,
    link: "https://wordcloudapi.com/",
    description: "Easily create word clouds",
    comments: [],
    likes: 0,
  },
  {
    name: "Auth0",
    category: "Auth",
    key: true,
    link: "",
    description:
      "Easy to implement, adaptable authentication and authorization platform",
    comments: [],
    likes: 0,
  },
  {
    name: "Auth0",
    category: "Auth",
    key: false,
    link: "https://auth0.com/",
    description:
      "Easy to implement, adaptable authentication and authorization platform",
    comments: [],
    likes: 0,
  },
  {
    name: "GetOTP",
    category: "Auth",
    key: true,
    link: "https://otp.dev/en/docs/",
    description: "Implement OTP flow quickly",
    comments: [],
    likes: 0,
  },
  {
    name: "Micro User Service",
    category: "Auth",
    key: true,
    link: "https://github.com/m3o/m3o",
    description: "User management and authentication",
    comments: [],
    likes: 0,
  },
  {
    name: "MojoAuth",
    category: "Auth",
    key: true,
    link: "https://mojoauth.com/",
    description: "Secure and modern passwordless authentication platform",
    comments: [],
    likes: 0,
  },
  {
    name: "Bitquery",
    category: "Blockchain",
    key: true,
    link: "https://ide.bitquery.io/",
    description: "Onchain GraphQL APIs & DEX APIs",
    comments: [],
    likes: 0,
  },
  {
    name: "Chainpoint",
    category: "Blockchain",
    key: false,
    link: "https://tierion.com/chainpoint/",
    description:
      "Chainpoint is a global network for anchoring data to the Bitcoin blockchain",
    comments: [],
    likes: 0,
  },
  {
    name: "Helium",
    category: "Blockchain",
    key: false,
    link: "https://docs.helium.com/",
    description:
      "Helium is a global, distributed network of Hotspots that create public, long-range wireless coverage",
    comments: [],
    likes: 0,
  },
  {
    name: "Nownodes",
    category: "Blockchain",
    key: true,
    link: "https://nownodes.io/",
    description:
      "Blockchain-as-a-service solution that provides high-quality connection via API",
    comments: [],
    likes: 0,
  },
  {
    name: "The Graph",
    category: "Blockchain",
    key: true,
    link: "https://thegraph.com/",
    description:
      "Indexing protocol for querying networks like Ethereum with GraphQL",
    comments: [],
    likes: 0,
  },

  {
    name: "A Bíblia Digital",
    category: "Books",
    key: true,
    link: "https://www.abibliadigital.com.br/en",
    description:
      "Do not worry about managing the multiple versions of the Bible",
    comments: [],
    likes: 0,
  },
  {
    name: "Bible-api",
    category: "Books",
    key: false,
    link: "https://bible-api.com/",
    description: "	Free Bible API with multiple languages",
    comments: [],
    likes: 0,
  }, 
  {
    name: "Crossref Metadata Search",
    category: "Books",
    key: false,
    link: "https://github.com/CrossRef/rest-api-doc",
    description: "Books & Articles Metadata",
    comments: [],
    likes: 0,
  },
  {
    name: "Quran",
    category: "Books",
    key: false,
    link: "https://api-docs.io/",
    description: "RESTful Quran API with multiple languages",
    comments: [],
    likes: 0,
  },
  {
    name: "Rig Veda",
    category: "Books",
    key: false,
    link: "https://aninditabasu.github.io/indica/html/rv.html",
    description:
      "Gods and poets, their categories, and the verse meters, with the mandal and sukta number",
    comments: [],
    likes: 0,
  },
  {
    name: "Apache Superset",
    category: "Business",
    key: true,
    link: "https://superset.apache.org/docs/api/",
    description:
      "API to manage your BI dashboards and data sources on Superset",
    comments: [],
    likes: 0,
  },
  {
    name: "Domainsdb.info",
    category: "Business",
    key: false,
    link: "https://domainsdb.info/",
    description: "Registered Domain Names Search",
    comments: [],
    likes: 0,
  },
  {
    name: "markerapi",
    category: "Business",
    key: false,
    link: "https://markerapi.com/",
    description: "Trademark Search",
    comments: [],
    likes: 0,
  },
  {
    name: "Tenders in Hungary",
    category: "Business",
    key: false,
    link: "https://tenders.guru/hu/api",
    description: "Get data for procurements in Hungary in JSON format",
    comments: [],
    likes: 0,
  },
  {
    name: "Redash",
    category: "Business",
    key: true,
    link: "https://redash.io/help/user-guide/integrations-and-api/api",
    description: "Access your queries and dashboards on Redash",
    comments: [],
    likes: 0,
  },
  {
    name: "Hebrew Calendar",
    category: "Calendar",
    key: false,
    link: "https://www.hebcal.com/home/developer-apis",
    description:
      " Calendar	Convert between Gregorian and Hebrew, fetch Shabbat and Holiday times, etc",
    comments: [],
    likes: 0,
  },

  {
    name: "Checkiday - National Holiday API",
    category: "Calendar",
    key: true,
    link: "https://apilayer.com/marketplace/checkiday-api",
    description:
      "Industry-leading Holiday API. Over 5,000 holidays and thousands of descriptions. Trusted by the World’s leading companies",
    comments: [],
    likes: 0,
  },
  {
    name: "Google Calendar",
    category: "Calendar",
    key: false,
    link: "https://developers.google.com/calendar",
    description: "Display, create and modify Google calendar events",
    comments: [],
    likes: 0,
  },
  {
    name: "Google Calendar",
    category: "Calendar",
    key: false,
    link: "https://developers.google.com/calendar",
    description: "Display, create and modify Google calendar events",
    comments: [],
    likes: 0,
  },

  {
    name: "Box",
    category: "Cloud Storage & File Sharing",
    key: false,
    link: "https://developer.box.com/",
    description: "File Sharing and Storage",
    comments: [],
    likes: 0,
  },
  {
    name: "ddownload",
    category: "Cloud Storage & File Sharing",
    key: true,
    link: "https://ddownload.com/api",
    description: "File Sharing and Storage",
    comments: [],
    likes: 0,
  },
  {
    name: "File.io",
    category: "Cloud Storage & File Sharing",
    key: false,
    link: "https://www.file.io/",
    description: "Super simple file sharing, convenient, anonymous and secure",
    comments: [],
    likes: 0,
  },
  {
    name: "Dropbox",
    category: "Cloud Storage & File Sharing",
    key: false,
    link: "https://www.dropbox.com/developers",
    description: "File Sharing and Storage",
    comments: [],
    likes: 0,
  },
  {
    name: "OneDrive",
    category: "Cloud Storage & File Sharing",
    key: false,
    link: "https://developer.microsoft.com/en-us/onedrive",
    description: "File Sharing and Storage",
    comments: [],
    likes: 0,
  },//3rd
  {
    name: "Azure",
    category: "Continuous Integration",
    key: true,
    link: "https://learn.microsoft.com/en-us/rest/api/resourcehealth/",
    description:
      "Resource health helps you diagnose and get support when an Azure issue impacts your resources",
    comments: [],
    likes: 0,
  },
  {
    name: "Buddy",
    category: "Continuous Integration",
    key: true,
    link: "https://buddy.works/docs/api/getting-started/overview",
    description:
      "The fastest continuous integration and continuous delivery platform",
    comments: [],
    likes: 0,
  },
  {
    name: "CircleCI",
    category: "Continuous Integration",
    key: false,
    link: "https://circleci.com/docs/api/v1/index.html#circleci-v1-api-overview",
    description:
      "Automate the software development process using continuous integration and continuous delivery",
    comments: [],
    likes: 0,
  },
  {
    name: "Codeship",
    category: "Continuous Integration",
    key: true,
    link: "https://docs.cloudbees.com/docs/cloudbees-codeship/latest/api-overview/",
    description: "Codeship is a Continuous Integration Platform in the cloud",
    comments: [],
    likes: 0,
  },
  {
    name: "Alchemy Ethereum",
    category: "Cryptocurrency",
    key: true,
    link: "https://docs.alchemy.com/",
    description: "Ethereum Node-as-a-Service Provider",
    comments: [],
    likes: 0,
  },
  {
    name: "Binance",
    category: "Cryptocurrency",
    key: true,
    link: "https://github.com/binance/binance-spot-api-docs",
    description: "Exchange for Trading Cryptocurrencies based in China",
    comments: [],
    likes: 0,
  },

  {
    name: "Bitfinex",
    category: "Cryptocurrency",
    key: true,
    link: "https://docs.bitfinex.com/docs/introduction",
    description: "Cryptocurrency Trading Platform",
    comments: [],
    likes: 0,
  },

  {
    name: "CoinCap",
    category: "Cryptocurrency",
    key: false,
    link: "https://docs.coincap.io/",
    description: "Real time Cryptocurrency prices through a RESTful API",
    comments: [],
    likes: 0,
  },
  {
    name: "Coinlore",
    category: "Cryptocurrency",
    key: false,
    link: "https://www.coinlore.com/cryptocurrency-data-api",
    description: "Cryptocurrencies prices, volume and more",
    comments: [],
    likes: 0,
  },
  {
    name: "Gemini",
    category: "Cryptocurrency",
    key: false,
    link: "https://docs.gemini.com/rest-api/",
    description: "Cryptocurrencies Exchange",
    comments: [],
    likes: 0,
  },
  {
    name: "Mempool",
    category: "Cryptocurrency",
    key: false,
    link: "https://mempool.space/docs/api",
    description: "Bitcoin API Service focusing on the transaction fee",
    comments: [],
    likes: 0,
  },
  {
    name: "Mempool",
    category: "Cryptocurrency",
    key: false,
    link: "https://www.mercadobitcoin.com.br/api-doc/",
    description: "Bitcoin API Service focusing on the transaction fee",
    comments: [],
    likes: 0,
  },
  {
    name: "Messari",
    category: "Cryptocurrency",
    key: false,
    link: "https://messari.io/api",
    description: "Provides API endpoints for thousands of crypto assets",
    comments: [],
    likes: 0,
  },
  {
    name: "1Forge",
    category: "Currency Exchange",
    key: true,
    link: "https://1forge.com/api",
    description: "Forex currency market data",
    comments: [],
    likes: 0,
  },

  {
    name: "Amdoren",
    category: "Currency Exchange",
    key: true,
    link: "https://www.amdoren.com/currency-api/",
    description: "	Free currency API with over 150 currencies",
    comments: [],
    likes: 0,
  },
  {
    name: "Currency-api",
    category: "Currency Exchange",
    key: false,
    link: "https://github.com/fawazahmed0/currency-api#readme",
    description:
      "Free Currency Exchange Rates API with 150+ Currencies & No Rate Limits",
    comments: [],
    likes: 0,
  },
  {
    name: "apilayer fixer.io",
    category: "Currency Exchange",
    key: true,
    link: "https://fixer.io/",
    description: "Exchange rates and currency conversion",
    comments: [],
    likes: 0,
  },
  {
    name: "Economia.Awesome",
    category: "Currency Exchange",
    key: false,
    link: "https://docs.awesomeapi.com.br/api-de-moedas",
    description:
      "Portuguese free currency prices and conversion with no rate limits",
    comments: [],
    likes: 0,
  },
  {
    name: "Exchangerate.host",
    category: "Currency Exchang",
    key: false,
    link: "https://exchangerate.host/",
    description: "Free foreign exchange & crypto rates API",
    comments: [],
    likes: 0,
  },
  {
    name: "24 Pull Requests",
    category: "Development",
    key: false,
    link: "https://24pullrequests.com/api",
    description: "Project to promote open source collaboration during December",
    comments: [],
    likes: 0,
  },
  {
    name: "Abstract Screenshot",
    category: "Development",
    key: true,
    link: "https://www.abstractapi.com/api/website-screenshot-api",
    description: "Take programmatic screenshots of web pages from any website",
    comments: [],
    likes: 0,
  },
  {
    name: "ApiFlash",
    category: "Development",
    key: true,
    link: "https://apiflash.com/",
    description: "Chrome based screenshot API for developers",
    comments: [],
    likes: 0,
  },
  {
    name: "APIs.guru",
    category: "Development",
    key: false,
    link: "https://apis.guru/api-doc/",
    description:
      "Wikipedia for Web APIs, OpenAPI/Swagger specs for public APIs",
    comments: [],
    likes: 0,
  },
  {
    name: "Beeceptor",
    category: "Development",
    key: false,
    link: "https://beeceptor.com/",
    description: "Build a mock Rest API endpoint in seconds",
    comments: [],
    likes: 0,
  },
  {
    name: "Bored",
    category: "Development",
    key: false,
    link: "https://www.boredapi.com/",
    description: "Find random activities to fight boredom",
    comments: [],
    likes: 0,
  },
  {
    name: "CountAPI",
    category: "Development",
    key: false,
    link: "https://countapi.xyz/",
    description:
      "Free and simple counting service. You can use it to track page hits and specific events",
    comments: [],
    likes: 0,
  },
  {
    name: "DigitalOcean Status",
    category: "Development",
    key: false,
    link: "https://status.digitalocean.com/api",
    description: "Status of all DigitalOcean services",
    comments: [],
    likes: 0,
  },
  {
    name: "GitHub",
    category: "Development",
    key: false,
    link: "https://docs.github.com/en/rest",
    description:
      "Make use of GitHub repositories, code and user info programmatically",
    comments: [],
    likes: 0,
  },
  {
    name: "Google Fonts",
    category: "Development",
    key: true,
    link: "https://developers.google.com/fonts/docs/developer_api",
    description: "Metadata for all families served by Google Fonts",
    comments: [],
    likes: 0,
  },
];

//second batch

// {
//   {
//     name: "",
//     category: "",
//     key: false,
//     link: "",
//     description: "",
//     comments: [],
//     likes: 0,
//   },
//   {
//     name: "",
//     category: "",
//     key: false,
//     link: "",
//     description: "",
//     comments: [],
//     likes: 0,
//   },
// }

//  APIList.map(async (api: APIType) => {
//       const { name, category, link, description, key, comments, likes } = api;
//       try {
//         const response = await axios.post("http://localhost:3000/APIs/", {
//           name: name,
//           category: category,
//           link: link,
//           description: description,
//           key: key,
//           comments: comments,
//           likes: likes,
//         });
//         console.log(response.data);
//       } catch (error) {
//         console.error(error);
//       }
//     });
